### ISSUE TITLE
backbone object has no attribute 'init_weight' when training 

### ISSUE THREAD

**Issue by Itay2805** [SangbumChoi/MobileHumanPose#3]
When trying each of the backbones I am getting the following error (using LPRES as example, but same with all networks):
```
============================================================
LPRES BackBone Generated
============================================================
Traceback (most recent call last):
  File "main/train.py", line 84, in <module>
    main()
  File "main/train.py", line 39, in main
    trainer._make_model()
  File "main/../common/base.py", line 125, in _make_model
    model = get_pose_net(self.backbone, True, self.joint_num)
  File "main/model.py", line 83, in get_pose_net
    model.backbone.init_weight()
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LpNetResConcat' object has no attribute 'init_weight'
``` 
When looking at the commit history the problem arrived at this commit  bdbc6c14a58d857cab7b654fd02a356ae4b9c6c7

**Comment by SangbumChoi** [comment]
@Itay2805 at the moment you can just get rid of the function of .init_weight function. However it will be fixed ASAP!

**Comment by SangbumChoi** [comment]
@Itay2805 please retry this is fixed in https://github.com/SangbumChoi/MobileHumanPose/commit/fb16b4dec94f8b0e87d0a233606ed280c248939c
